/*
 * generated by Xtext
 */
package cl.pleiad.ram;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TextramRuntimeModule extends cl.pleiad.ram.AbstractTextramRuntimeModule {

}
