/*
* generated by Xtext
*/
package cl.pleiad.ram;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TextramStandaloneSetup extends TextramStandaloneSetupGenerated{

	public static void doSetup() {
		new TextramStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

