/*
* generated by Xtext
*/
package cl.uchile.pleiad;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TextRAMStandaloneSetup extends TextRAMStandaloneSetupGenerated{

	public static void doSetup() {
		new TextRAMStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

