/*
* generated by Xtext
*/
package cl.uchile.pleiad.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TextRAMAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("cl/uchile/pleiad/parser/antlr/internal/InternalTextRAM.tokens");
	}
}
