/*
 * generated by Xtext
 */
package cl.uchile.pleiad.ui.contentassist

import cl.uchile.pleiad.ui.contentassist.AbstractTextRAMProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TextRAMProposalProvider extends AbstractTextRAMProposalProvider {
}
