/*
 * generated by Xtext
 */
package cl.uchile.pleiad.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import cl.uchile.pleiad.ui.internal.TextRAMActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TextRAMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TextRAMActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TextRAMActivator.getInstance().getInjector(TextRAMActivator.CL_UCHILE_PLEIAD_TEXTRAM);
	}
	
}
