/*
* generated by Xtext
*/
package cl.pleiad.ram.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TextramAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("cl/pleiad/ram/parser/antlr/internal/InternalTextram.tokens");
	}
}
