/*
* generated by Xtext
*/
package cl.pleiad.ram.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import cl.pleiad.ram.services.TextramGrammarAccess;

public class TextramParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TextramGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected cl.pleiad.ram.parser.antlr.internal.InternalTextramParser createParser(XtextTokenStream stream) {
		return new cl.pleiad.ram.parser.antlr.internal.InternalTextramParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public TextramGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TextramGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
