/*
 * generated by Xtext
 */
package cl.uchile.pleiad.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TextRAMUiModule extends cl.uchile.pleiad.ui.AbstractTextRAMUiModule {
	public TextRAMUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
