/*
* generated by Xtext
*/
package cl.uchile.pleiad;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TextRAMUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return cl.uchile.pleiad.ui.internal.TextRAMActivator.getInstance().getInjector("cl.uchile.pleiad.TextRAM");
	}
	
}
