/**
 * generated by Xtext
 */
package cl.uchile.pleiad.ui.contentassist;

import cl.uchile.pleiad.ui.contentassist.AbstractTextRAMProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class TextRAMProposalProvider extends AbstractTextRAMProposalProvider {
}
