/**
 * generated by Xtext
 */
package cl.uchile.pleiad.validation;

import cl.uchile.pleiad.validation.AbstractTextRAMValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TextRAMValidator extends AbstractTextRAMValidator {
}
