/*
* generated by Xtext
*/
package cl.uchile.pleiad.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import cl.uchile.pleiad.services.TextRAMGrammarAccess;

public class TextRAMParser extends AbstractContentAssistParser {
	
	@Inject
	private TextRAMGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected cl.uchile.pleiad.ui.contentassist.antlr.internal.InternalTextRAMParser createParser() {
		cl.uchile.pleiad.ui.contentassist.antlr.internal.InternalTextRAMParser result = new cl.uchile.pleiad.ui.contentassist.antlr.internal.InternalTextRAMParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getObjectTypeAccess().getAlternatives(), "rule__ObjectType__Alternatives");
					put(grammarAccess.getPrimitiveTypeAccess().getAlternatives(), "rule__PrimitiveType__Alternatives");
					put(grammarAccess.getTClassMemberAccess().getAlternatives(), "rule__TClassMember__Alternatives");
					put(grammarAccess.getElementBoundAccess().getAlternatives(), "rule__ElementBound__Alternatives");
					put(grammarAccess.getTAbstractMessagesAccess().getAlternatives(), "rule__TAbstractMessages__Alternatives");
					put(grammarAccess.getTValueSpecificationAccess().getAlternatives(), "rule__TValueSpecification__Alternatives");
					put(grammarAccess.getTTemporaryPropertyAccess().getAlternatives(), "rule__TTemporaryProperty__Alternatives");
					put(grammarAccess.getTInteractionAccess().getAlternatives(), "rule__TInteraction__Alternatives");
					put(grammarAccess.getTAbstractMessageAccess().getAlternatives(), "rule__TAbstractMessage__Alternatives");
					put(grammarAccess.getTTypedElementAccess().getAlternatives(), "rule__TTypedElement__Alternatives");
					put(grammarAccess.getTMessageAssignableFeatureAccess().getAlternatives(), "rule__TMessageAssignableFeature__Alternatives");
					put(grammarAccess.getVisibilityAccess().getAlternatives(), "rule__Visibility__Alternatives");
					put(grammarAccess.getInstantiationTypeAccess().getAlternatives(), "rule__InstantiationType__Alternatives");
					put(grammarAccess.getMessageSortAccess().getAlternatives(), "rule__MessageSort__Alternatives");
					put(grammarAccess.getReferenceTypeAccess().getAlternatives(), "rule__ReferenceType__Alternatives");
					put(grammarAccess.getInteractionOperatorKindAccess().getAlternatives(), "rule__InteractionOperatorKind__Alternatives");
					put(grammarAccess.getOcurrenceTypeAccess().getAlternatives(), "rule__OcurrenceType__Alternatives");
					put(grammarAccess.getTLifelineReferenceTypeAccess().getAlternatives(), "rule__TLifelineReferenceType__Alternatives");
					put(grammarAccess.getTAspectAccess().getGroup(), "rule__TAspect__Group__0");
					put(grammarAccess.getTAspectAccess().getGroup_2(), "rule__TAspect__Group_2__0");
					put(grammarAccess.getTAspectAccess().getGroup_2_1(), "rule__TAspect__Group_2_1__0");
					put(grammarAccess.getTAspectAccess().getGroup_5(), "rule__TAspect__Group_5__0");
					put(grammarAccess.getTAspectAccess().getGroup_5_3(), "rule__TAspect__Group_5_3__0");
					put(grammarAccess.getTAspectAccess().getGroup_6(), "rule__TAspect__Group_6__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getTAbstractMessageViewAccess().getGroup(), "rule__TAbstractMessageView__Group__0");
					put(grammarAccess.getTAbstractMessageViewAccess().getGroup_4(), "rule__TAbstractMessageView__Group_4__0");
					put(grammarAccess.getTStructuralViewAccess().getGroup(), "rule__TStructuralView__Group__0");
					put(grammarAccess.getTStructuralViewAccess().getGroup_3(), "rule__TStructuralView__Group_3__0");
					put(grammarAccess.getTStructuralViewAccess().getGroup_4(), "rule__TStructuralView__Group_4__0");
					put(grammarAccess.getTStructuralViewAccess().getGroup_4_3(), "rule__TStructuralView__Group_4_3__0");
					put(grammarAccess.getTClassAccess().getGroup(), "rule__TClass__Group__0");
					put(grammarAccess.getTClassAccess().getGroup_5(), "rule__TClass__Group_5__0");
					put(grammarAccess.getTClassAccess().getGroup_7(), "rule__TClass__Group_7__0");
					put(grammarAccess.getTClassAccess().getGroup_7_1(), "rule__TClass__Group_7_1__0");
					put(grammarAccess.getTAttributeAccess().getGroup(), "rule__TAttribute__Group__0");
					put(grammarAccess.getTOperationAccess().getGroup(), "rule__TOperation__Group__0");
					put(grammarAccess.getTOperationAccess().getGroup_9(), "rule__TOperation__Group_9__0");
					put(grammarAccess.getTOperationAccess().getGroup_9_1(), "rule__TOperation__Group_9_1__0");
					put(grammarAccess.getTParameterAccess().getGroup(), "rule__TParameter__Group__0");
					put(grammarAccess.getTAssociationAccess().getGroup(), "rule__TAssociation__Group__0");
					put(grammarAccess.getTAssociationEndAccess().getGroup(), "rule__TAssociationEnd__Group__0");
					put(grammarAccess.getTAssociationEndAccess().getGroup_1(), "rule__TAssociationEnd__Group_1__0");
					put(grammarAccess.getTInstantiationHeaderAccess().getGroup(), "rule__TInstantiationHeader__Group__0");
					put(grammarAccess.getTInstantiationHeaderAccess().getGroup_2(), "rule__TInstantiationHeader__Group_2__0");
					put(grammarAccess.getInstantiationAccess().getGroup(), "rule__Instantiation__Group__0");
					put(grammarAccess.getInstantiationAccess().getGroup_1(), "rule__Instantiation__Group_1__0");
					put(grammarAccess.getInstantiationAccess().getGroup_1_2(), "rule__Instantiation__Group_1_2__0");
					put(grammarAccess.getTClassifierMappingAccess().getGroup(), "rule__TClassifierMapping__Group__0");
					put(grammarAccess.getTClassifierMappingAccess().getGroup_2(), "rule__TClassifierMapping__Group_2__0");
					put(grammarAccess.getTClassifierMappingAccess().getGroup_2_2(), "rule__TClassifierMapping__Group_2_2__0");
					put(grammarAccess.getTClassifierMappingAccess().getGroup_6(), "rule__TClassifierMapping__Group_6__0");
					put(grammarAccess.getTClassifierMappingAccess().getGroup_6_2(), "rule__TClassifierMapping__Group_6_2__0");
					put(grammarAccess.getTMessageViewAccess().getGroup(), "rule__TMessageView__Group__0");
					put(grammarAccess.getTMessageViewAccess().getGroup_9(), "rule__TMessageView__Group_9__0");
					put(grammarAccess.getTMessageViewAccess().getGroup_9_1(), "rule__TMessageView__Group_9_1__0");
					put(grammarAccess.getTMessageViewAccess().getGroup_11(), "rule__TMessageView__Group_11__0");
					put(grammarAccess.getTMessageViewAccess().getGroup_11_2(), "rule__TMessageView__Group_11_2__0");
					put(grammarAccess.getTMessageViewAccess().getGroup_12(), "rule__TMessageView__Group_12__0");
					put(grammarAccess.getTMessageViewAccess().getGroup_12_2(), "rule__TMessageView__Group_12_2__0");
					put(grammarAccess.getTAspectMessageViewAccess().getGroup(), "rule__TAspectMessageView__Group__0");
					put(grammarAccess.getTAspectMessageViewAccess().getGroup_6(), "rule__TAspectMessageView__Group_6__0");
					put(grammarAccess.getTAspectMessageViewAccess().getGroup_10(), "rule__TAspectMessageView__Group_10__0");
					put(grammarAccess.getTAspectMessageViewAccess().getGroup_10_1(), "rule__TAspectMessageView__Group_10_1__0");
					put(grammarAccess.getTAspectMessageViewAccess().getGroup_15(), "rule__TAspectMessageView__Group_15__0");
					put(grammarAccess.getTLifelineAccess().getGroup(), "rule__TLifeline__Group__0");
					put(grammarAccess.getTLifelineAccess().getGroup_5(), "rule__TLifeline__Group_5__0");
					put(grammarAccess.getTLifelineAccess().getGroup_5_2(), "rule__TLifeline__Group_5_2__0");
					put(grammarAccess.getTReferenceAccess().getGroup(), "rule__TReference__Group__0");
					put(grammarAccess.getTLocalAttributeAccess().getGroup(), "rule__TLocalAttribute__Group__0");
					put(grammarAccess.getTLocalAttributeAccess().getGroup_2(), "rule__TLocalAttribute__Group_2__0");
					put(grammarAccess.getTOcurrenceAccess().getGroup(), "rule__TOcurrence__Group__0");
					put(grammarAccess.getTInteractionMessageAccess().getGroup(), "rule__TInteractionMessage__Group__0");
					put(grammarAccess.getTInteractionMessageAccess().getGroup_4(), "rule__TInteractionMessage__Group_4__0");
					put(grammarAccess.getTCombinedFragmentAccess().getGroup(), "rule__TCombinedFragment__Group__0");
					put(grammarAccess.getTCombinedFragmentAccess().getGroup_8(), "rule__TCombinedFragment__Group_8__0");
					put(grammarAccess.getTMessageAccess().getGroup(), "rule__TMessage__Group__0");
					put(grammarAccess.getTMessageAccess().getGroup_0(), "rule__TMessage__Group_0__0");
					put(grammarAccess.getTMessageAccess().getGroup_4(), "rule__TMessage__Group_4__0");
					put(grammarAccess.getTMessageAccess().getGroup_4_1(), "rule__TMessage__Group_4_1__0");
					put(grammarAccess.getTAspectAccess().getNameAssignment_1(), "rule__TAspect__NameAssignment_1");
					put(grammarAccess.getTAspectAccess().getHeaderInstantiationsAssignment_2_0(), "rule__TAspect__HeaderInstantiationsAssignment_2_0");
					put(grammarAccess.getTAspectAccess().getHeaderInstantiationsAssignment_2_1_1(), "rule__TAspect__HeaderInstantiationsAssignment_2_1_1");
					put(grammarAccess.getTAspectAccess().getStructuralViewAssignment_4(), "rule__TAspect__StructuralViewAssignment_4");
					put(grammarAccess.getTAspectAccess().getInstantiationsAssignment_5_2(), "rule__TAspect__InstantiationsAssignment_5_2");
					put(grammarAccess.getTAspectAccess().getInstantiationsAssignment_5_3_1(), "rule__TAspect__InstantiationsAssignment_5_3_1");
					put(grammarAccess.getTAspectAccess().getMessageViewsAssignment_6_2(), "rule__TAspect__MessageViewsAssignment_6_2");
					put(grammarAccess.getTAbstractMessageViewAccess().getLifelinesAssignment_3(), "rule__TAbstractMessageView__LifelinesAssignment_3");
					put(grammarAccess.getTAbstractMessageViewAccess().getLifelinesAssignment_4_1(), "rule__TAbstractMessageView__LifelinesAssignment_4_1");
					put(grammarAccess.getTAbstractMessageViewAccess().getMessagesAssignment_6(), "rule__TAbstractMessageView__MessagesAssignment_6");
					put(grammarAccess.getTAbstractMessageViewAccess().getMessagesAssignment_7(), "rule__TAbstractMessageView__MessagesAssignment_7");
					put(grammarAccess.getTStructuralViewAccess().getClassesAssignment_3_0(), "rule__TStructuralView__ClassesAssignment_3_0");
					put(grammarAccess.getTStructuralViewAccess().getClassesAssignment_3_1(), "rule__TStructuralView__ClassesAssignment_3_1");
					put(grammarAccess.getTStructuralViewAccess().getTAssociationsAssignment_4_2(), "rule__TStructuralView__TAssociationsAssignment_4_2");
					put(grammarAccess.getTStructuralViewAccess().getTAssociationsAssignment_4_3_1(), "rule__TStructuralView__TAssociationsAssignment_4_3_1");
					put(grammarAccess.getTClassAccess().getAbstractAssignment_1(), "rule__TClass__AbstractAssignment_1");
					put(grammarAccess.getTClassAccess().getPartialAssignment_3(), "rule__TClass__PartialAssignment_3");
					put(grammarAccess.getTClassAccess().getNameAssignment_4(), "rule__TClass__NameAssignment_4");
					put(grammarAccess.getTClassAccess().getPartialSuperTypeAssignment_5_1(), "rule__TClass__PartialSuperTypeAssignment_5_1");
					put(grammarAccess.getTClassAccess().getSuperTypesAssignment_5_2(), "rule__TClass__SuperTypesAssignment_5_2");
					put(grammarAccess.getTClassAccess().getMembersAssignment_7_0(), "rule__TClass__MembersAssignment_7_0");
					put(grammarAccess.getTClassAccess().getMembersAssignment_7_1_1(), "rule__TClass__MembersAssignment_7_1_1");
					put(grammarAccess.getTAttributeAccess().getStaticAssignment_0(), "rule__TAttribute__StaticAssignment_0");
					put(grammarAccess.getTAttributeAccess().getTypeAssignment_1(), "rule__TAttribute__TypeAssignment_1");
					put(grammarAccess.getTAttributeAccess().getPartialAssignment_2(), "rule__TAttribute__PartialAssignment_2");
					put(grammarAccess.getTAttributeAccess().getNameAssignment_3(), "rule__TAttribute__NameAssignment_3");
					put(grammarAccess.getTOperationAccess().getAbstractAssignment_1(), "rule__TOperation__AbstractAssignment_1");
					put(grammarAccess.getTOperationAccess().getStaticAssignment_2(), "rule__TOperation__StaticAssignment_2");
					put(grammarAccess.getTOperationAccess().getVisibilityAssignment_3(), "rule__TOperation__VisibilityAssignment_3");
					put(grammarAccess.getTOperationAccess().getPartialReturnTypeAssignment_4(), "rule__TOperation__PartialReturnTypeAssignment_4");
					put(grammarAccess.getTOperationAccess().getReturnTypeAssignment_5(), "rule__TOperation__ReturnTypeAssignment_5");
					put(grammarAccess.getTOperationAccess().getPartialAssignment_6(), "rule__TOperation__PartialAssignment_6");
					put(grammarAccess.getTOperationAccess().getNameAssignment_7(), "rule__TOperation__NameAssignment_7");
					put(grammarAccess.getTOperationAccess().getParametersAssignment_9_0(), "rule__TOperation__ParametersAssignment_9_0");
					put(grammarAccess.getTOperationAccess().getParametersAssignment_9_1_1(), "rule__TOperation__ParametersAssignment_9_1_1");
					put(grammarAccess.getTParameterAccess().getPartialTypeAssignment_0(), "rule__TParameter__PartialTypeAssignment_0");
					put(grammarAccess.getTParameterAccess().getTypeAssignment_1(), "rule__TParameter__TypeAssignment_1");
					put(grammarAccess.getTParameterAccess().getNameAssignment_2(), "rule__TParameter__NameAssignment_2");
					put(grammarAccess.getTAssociationAccess().getFromEndAssignment_1(), "rule__TAssociation__FromEndAssignment_1");
					put(grammarAccess.getTAssociationAccess().getReferenceTypeAssignment_2(), "rule__TAssociation__ReferenceTypeAssignment_2");
					put(grammarAccess.getTAssociationAccess().getToEndAssignment_4(), "rule__TAssociation__ToEndAssignment_4");
					put(grammarAccess.getTAssociationAccess().getNameAssignment_6(), "rule__TAssociation__NameAssignment_6");
					put(grammarAccess.getTAssociationEndAccess().getLowerBoundAssignment_1_0(), "rule__TAssociationEnd__LowerBoundAssignment_1_0");
					put(grammarAccess.getTAssociationEndAccess().getUpperBoundAssignment_2(), "rule__TAssociationEnd__UpperBoundAssignment_2");
					put(grammarAccess.getTAssociationEndAccess().getClassReferenceAssignment_3(), "rule__TAssociationEnd__ClassReferenceAssignment_3");
					put(grammarAccess.getTInstantiationHeaderAccess().getTypeAssignment_0(), "rule__TInstantiationHeader__TypeAssignment_0");
					put(grammarAccess.getTInstantiationHeaderAccess().getExternalAspectsAssignment_1(), "rule__TInstantiationHeader__ExternalAspectsAssignment_1");
					put(grammarAccess.getTInstantiationHeaderAccess().getExternalAspectsAssignment_2_1(), "rule__TInstantiationHeader__ExternalAspectsAssignment_2_1");
					put(grammarAccess.getInstantiationAccess().getExternalAspectAssignment_0(), "rule__Instantiation__ExternalAspectAssignment_0");
					put(grammarAccess.getInstantiationAccess().getMappingsAssignment_1_1(), "rule__Instantiation__MappingsAssignment_1_1");
					put(grammarAccess.getInstantiationAccess().getMappingsAssignment_1_2_1(), "rule__Instantiation__MappingsAssignment_1_2_1");
					put(grammarAccess.getTClassifierMappingAccess().getPartialFromElementAssignment_0(), "rule__TClassifierMapping__PartialFromElementAssignment_0");
					put(grammarAccess.getTClassifierMappingAccess().getFromElementAssignment_1(), "rule__TClassifierMapping__FromElementAssignment_1");
					put(grammarAccess.getTClassifierMappingAccess().getFromMembersAssignment_2_1(), "rule__TClassifierMapping__FromMembersAssignment_2_1");
					put(grammarAccess.getTClassifierMappingAccess().getFromMembersAssignment_2_2_1(), "rule__TClassifierMapping__FromMembersAssignment_2_2_1");
					put(grammarAccess.getTClassifierMappingAccess().getPartialToElementAssignment_4(), "rule__TClassifierMapping__PartialToElementAssignment_4");
					put(grammarAccess.getTClassifierMappingAccess().getToElementAssignment_5(), "rule__TClassifierMapping__ToElementAssignment_5");
					put(grammarAccess.getTClassifierMappingAccess().getToMembersAssignment_6_1(), "rule__TClassifierMapping__ToMembersAssignment_6_1");
					put(grammarAccess.getTClassifierMappingAccess().getToMembersAssignment_6_2_1(), "rule__TClassifierMapping__ToMembersAssignment_6_2_1");
					put(grammarAccess.getTMessageViewAccess().getCreateAssignment_2(), "rule__TMessageView__CreateAssignment_2");
					put(grammarAccess.getTMessageViewAccess().getPartialClassAssignment_3(), "rule__TMessageView__PartialClassAssignment_3");
					put(grammarAccess.getTMessageViewAccess().getClassAssignment_4(), "rule__TMessageView__ClassAssignment_4");
					put(grammarAccess.getTMessageViewAccess().getPartialOperationAssignment_6(), "rule__TMessageView__PartialOperationAssignment_6");
					put(grammarAccess.getTMessageViewAccess().getSpecifiesAssignment_7(), "rule__TMessageView__SpecifiesAssignment_7");
					put(grammarAccess.getTMessageViewAccess().getArgumentsAssignment_9_0(), "rule__TMessageView__ArgumentsAssignment_9_0");
					put(grammarAccess.getTMessageViewAccess().getArgumentsAssignment_9_1_1(), "rule__TMessageView__ArgumentsAssignment_9_1_1");
					put(grammarAccess.getTMessageViewAccess().getAffectedByAssignment_11_1(), "rule__TMessageView__AffectedByAssignment_11_1");
					put(grammarAccess.getTMessageViewAccess().getAffectedByAssignment_11_2_1(), "rule__TMessageView__AffectedByAssignment_11_2_1");
					put(grammarAccess.getTMessageViewAccess().getInteractionMessagesAssignment_12_1(), "rule__TMessageView__InteractionMessagesAssignment_12_1");
					put(grammarAccess.getTMessageViewAccess().getInteractionMessagesAssignment_12_2_1(), "rule__TMessageView__InteractionMessagesAssignment_12_2_1");
					put(grammarAccess.getTAspectMessageViewAccess().getNameAssignment_2(), "rule__TAspectMessageView__NameAssignment_2");
					put(grammarAccess.getTAspectMessageViewAccess().getCreateAssignment_5(), "rule__TAspectMessageView__CreateAssignment_5");
					put(grammarAccess.getTAspectMessageViewAccess().getPartialClassAssignment_6_0(), "rule__TAspectMessageView__PartialClassAssignment_6_0");
					put(grammarAccess.getTAspectMessageViewAccess().getClassAssignment_6_1(), "rule__TAspectMessageView__ClassAssignment_6_1");
					put(grammarAccess.getTAspectMessageViewAccess().getPartialOperationAssignment_7(), "rule__TAspectMessageView__PartialOperationAssignment_7");
					put(grammarAccess.getTAspectMessageViewAccess().getSpecifiesAssignment_8(), "rule__TAspectMessageView__SpecifiesAssignment_8");
					put(grammarAccess.getTAspectMessageViewAccess().getArgumentsAssignment_10_0(), "rule__TAspectMessageView__ArgumentsAssignment_10_0");
					put(grammarAccess.getTAspectMessageViewAccess().getArgumentsAssignment_10_1_1(), "rule__TAspectMessageView__ArgumentsAssignment_10_1_1");
					put(grammarAccess.getTAspectMessageViewAccess().getInteractionMessagesAssignment_14(), "rule__TAspectMessageView__InteractionMessagesAssignment_14");
					put(grammarAccess.getTAspectMessageViewAccess().getInteractionMessagesAssignment_15_1(), "rule__TAspectMessageView__InteractionMessagesAssignment_15_1");
					put(grammarAccess.getTLifelineAccess().getStaticAssignment_0(), "rule__TLifeline__StaticAssignment_0");
					put(grammarAccess.getTLifelineAccess().getReferenceTypeAssignment_1(), "rule__TLifeline__ReferenceTypeAssignment_1");
					put(grammarAccess.getTLifelineAccess().getNameAssignment_2(), "rule__TLifeline__NameAssignment_2");
					put(grammarAccess.getTLifelineAccess().getRepresentsAssignment_4(), "rule__TLifeline__RepresentsAssignment_4");
					put(grammarAccess.getTLifelineAccess().getLocalPropertiesAssignment_5_1(), "rule__TLifeline__LocalPropertiesAssignment_5_1");
					put(grammarAccess.getTLifelineAccess().getLocalPropertiesAssignment_5_2_1(), "rule__TLifeline__LocalPropertiesAssignment_5_2_1");
					put(grammarAccess.getTDummyValueSpecificationAccess().getDummyAssignment(), "rule__TDummyValueSpecification__DummyAssignment");
					put(grammarAccess.getTReferenceAccess().getNameAssignment_0(), "rule__TReference__NameAssignment_0");
					put(grammarAccess.getTReferenceAccess().getPartialClassAssignment_2(), "rule__TReference__PartialClassAssignment_2");
					put(grammarAccess.getTReferenceAccess().getReferenceAssignment_3(), "rule__TReference__ReferenceAssignment_3");
					put(grammarAccess.getTLocalAttributeAccess().getTypeAssignment_0(), "rule__TLocalAttribute__TypeAssignment_0");
					put(grammarAccess.getTLocalAttributeAccess().getNameAssignment_1(), "rule__TLocalAttribute__NameAssignment_1");
					put(grammarAccess.getTLocalAttributeAccess().getValueAssignment_2_1(), "rule__TLocalAttribute__ValueAssignment_2_1");
					put(grammarAccess.getTOcurrenceAccess().getLeftLifelineAssignment_0(), "rule__TOcurrence__LeftLifelineAssignment_0");
					put(grammarAccess.getTOcurrenceAccess().getOcurrenceTypeAssignment_2(), "rule__TOcurrence__OcurrenceTypeAssignment_2");
					put(grammarAccess.getTInteractionMessageAccess().getLeftLifelineAssignment_0(), "rule__TInteractionMessage__LeftLifelineAssignment_0");
					put(grammarAccess.getTInteractionMessageAccess().getCreateAssignment_2(), "rule__TInteractionMessage__CreateAssignment_2");
					put(grammarAccess.getTInteractionMessageAccess().getRightLifelineAssignment_3(), "rule__TInteractionMessage__RightLifelineAssignment_3");
					put(grammarAccess.getTInteractionMessageAccess().getMessageAssignment_4_1(), "rule__TInteractionMessage__MessageAssignment_4_1");
					put(grammarAccess.getTCombinedFragmentAccess().getInteractionOperatorAssignment_0(), "rule__TCombinedFragment__InteractionOperatorAssignment_0");
					put(grammarAccess.getTCombinedFragmentAccess().getInteractionConstraintAssignment_2(), "rule__TCombinedFragment__InteractionConstraintAssignment_2");
					put(grammarAccess.getTCombinedFragmentAccess().getContainersAssignment_5(), "rule__TCombinedFragment__ContainersAssignment_5");
					put(grammarAccess.getTCombinedFragmentAccess().getContainersAssignment_6(), "rule__TCombinedFragment__ContainersAssignment_6");
					put(grammarAccess.getTCombinedFragmentAccess().getElseContainersAssignment_8_2(), "rule__TCombinedFragment__ElseContainersAssignment_8_2");
					put(grammarAccess.getTCombinedFragmentAccess().getElseContainersAssignment_8_3(), "rule__TCombinedFragment__ElseContainersAssignment_8_3");
					put(grammarAccess.getTReturnMessageAccess().getAssignToAssignment(), "rule__TReturnMessage__AssignToAssignment");
					put(grammarAccess.getTMessageAccess().getAssignToAssignment_0_0(), "rule__TMessage__AssignToAssignment_0_0");
					put(grammarAccess.getTMessageAccess().getPartialOperationAssignment_1(), "rule__TMessage__PartialOperationAssignment_1");
					put(grammarAccess.getTMessageAccess().getSignatureAssignment_2(), "rule__TMessage__SignatureAssignment_2");
					put(grammarAccess.getTMessageAccess().getArgumentsAssignment_4_0(), "rule__TMessage__ArgumentsAssignment_4_0");
					put(grammarAccess.getTMessageAccess().getArgumentsAssignment_4_1_1(), "rule__TMessage__ArgumentsAssignment_4_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			cl.uchile.pleiad.ui.contentassist.antlr.internal.InternalTextRAMParser typedParser = (cl.uchile.pleiad.ui.contentassist.antlr.internal.InternalTextRAMParser) parser;
			typedParser.entryRuleAspect();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public TextRAMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TextRAMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
