/*
* generated by Xtext
*/
package cl.uchile.pleiad.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import cl.uchile.pleiad.services.TextRAMGrammarAccess;

public class TextRAMParser extends AbstractContentAssistParser {
	
	@Inject
	private TextRAMGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected cl.uchile.pleiad.ui.contentassist.antlr.internal.InternalTextRAMParser createParser() {
		cl.uchile.pleiad.ui.contentassist.antlr.internal.InternalTextRAMParser result = new cl.uchile.pleiad.ui.contentassist.antlr.internal.InternalTextRAMParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getAspectAccess().getGroup(), "rule__Aspect__Group__0");
					put(grammarAccess.getStructuralViewAccess().getGroup(), "rule__StructuralView__Group__0");
					put(grammarAccess.getAspectAccess().getNameAssignment_1(), "rule__Aspect__NameAssignment_1");
					put(grammarAccess.getAspectAccess().getStructuralViewAssignment_3(), "rule__Aspect__StructuralViewAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			cl.uchile.pleiad.ui.contentassist.antlr.internal.InternalTextRAMParser typedParser = (cl.uchile.pleiad.ui.contentassist.antlr.internal.InternalTextRAMParser) parser;
			typedParser.entryRuleAspect();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public TextRAMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TextRAMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
