/**
 * generated by Xtext
 */
package cl.uchile.pleiad.serializer;

import cl.uchile.pleiad.serializer.AbstractTextRAMSyntacticSequencer;

@SuppressWarnings("all")
public class TextRAMSyntacticSequencer extends AbstractTextRAMSyntacticSequencer {
}
