/**
 * generated by Xtext
 */
package cl.uchile.pleiad.serializer;

import cl.uchile.pleiad.serializer.AbstractTextRAMSemanticSequencer;

@SuppressWarnings("all")
public class TextRAMSemanticSequencer extends AbstractTextRAMSemanticSequencer {
}
