/**
 * generated by Xtext
 */
package cl.pleiad.ram.ui.contentassist;

import cl.pleiad.ram.ui.contentassist.AbstractTextramProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class TextramProposalProvider extends AbstractTextramProposalProvider {
}
