/*
 * generated by Xtext
 */
package cl.pleiad.ram.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTextramValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(cl.pleiad.ram.textram.TextramPackage.eINSTANCE);
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://cs.mcgill.ca/sel/ram/2.1"));
		return result;
	}
}
