/*
 * generated by Xtext
 */
package cl.pleiad.ram.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TextramUiModule extends cl.pleiad.ram.ui.AbstractTextramUiModule {
	public TextramUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
