/**
 * generated by Xtext
 */
package cl.pleiad.ram.validation;

import cl.pleiad.ram.validation.AbstractTextramValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TextramValidator extends AbstractTextramValidator {
}
