/*
 * generated by Xtext
 */
package cl.pleiad.ram.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import cl.pleiad.ram.ui.internal.TextramActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TextramExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TextramActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TextramActivator.getInstance().getInjector(TextramActivator.CL_PLEIAD_RAM_TEXTRAM);
	}
	
}
